services:
  - type: web
    name: stock-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python api_stock_flask.py"
    envVars:
      - key: PORT
        value: 5000
